with probability>0.5 eventually species_1 > 0 
with probability>0.5 always a > 0 
with probability>0.5 next a > 0 
with probability>=0.9 never a>0
with probability >=1 INFINITELY-OFTEN a>0
with probability>=0.9 steady-state a>0
with probability >=1 a>=0 until b>=0
with probability >=1 a>=0 WEAK-UNTIL b>=0
with probability >=1 a>=0 release b>=0
with probability >=1 a>=0 follows b>=0
with probability >=1 a>=0 precedes b>=0